### ISSUE TITLE
FOMM crashes when attempting to work on Fallout3

### ISSUE THREAD

**Issue by GrantSP** [foesmm/fomm#21]
I have this tool working fine with FalloutNV and have never had any difficulties with it.
Just today I tried to use it with Fallout3 and after the game selector dialog asks which game it crashes with this message:

```
Wednesday, 24 December 2014 - 5:42:54 PM
 Fomm 0.14.11.9
 OS version: Microsoft Windows NT 6.1.7601 Service Pack 1

System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at Fomm.BackgroundWorkerProgressDialog.System.IDisposable.Dispose()
   at Fomm.InstallLogUpgraders.Upgrader.PerformUpgrade()
   at Fomm.InstallLogUpgraders.InstallLogUpgrader.UpgradeInstallLog()
   at Fomm.Program.Main(String[] args)
```

**Comment by ericred222** [comment]
i have the same sort of problem but for New Vegas

**Comment by EvilOssie** [comment]
I'm not sure that this will do it, but first thing I'd check are the overall settings...
 - on the 'General' tab, both 'associate with fomods' and 'associate with BSAs' need to be checked
 - on the game-title tab, be sure that the pathings are correct for 'mod directory', 'install info' and '* game title *' directories. 

I [i]think[/i] the error msg is saying that it can't find one or more. I think. Maybe. 

Would either of you do me a favor and let me know if this in fact did help, please?

**Comment by GrantSP** [comment]
No that can't work because the error occurs from the game selector box.
When I choose Fallout 3 the next dialog is this one:
http://puu.sh/e21V9/1cdcebb1b1.jpg
After clicking "Ok" the error is generated and the program crashes, or at the least, never initialises.
FOMM for Fallout 3 never gets to the GUI showing so no settings can be set.

**Comment by EvilOssie** [comment]
OK, I'm stumped...I have never seen that error msg before, so sorta-random questions come to mind in the hope of stumbling across the issue (some of them probably won't make sense, I'm thinking off the top of my head here)...

 - What version are you using? Are you also using the NMM?
 - Have you tried a total uninstall/reinstall of FOMM?
 - Yours is only acting up w/FO3, right? Is this from a retail disc(s) or the Steam version?
 - How old is your game build, and are the build itself, your FOMM install, and fomod directory all on the same drive?
 - How many active mods do you have currently, and how many fomods in total are there?
 - Did you have any issues with building fomods, ie - error messages, failed builds, etc?

I still wonder if the problem is in the pathing somehow/somewhere, but I have no idea why I'm thinking this either.

**Comment by GrantSP** [comment]
* Version 0.14.11.9
* Not using NMM but I am using MO. However it occurs outside of any mod manager environment
* My FalloutNV is the latest Steam release, my Fallout 3 version is a disc version from many years back
* Both the Fallout games were installed only months ago as I now am offering support for MO and needed all the supported games loaded
* All my software is on the same drive, I am on a gaming laptop
* Both Fallouts are bare minimum but as mentioned, outside of MO there are ONLY the vanilla assets loaded
* No building of FOMODs has been done. At this stage it is only for the purpose of provide support with installation of them in MO when the MO plugin can't handle heavily scripted FOMODs.

**Comment by EvilOssie** [comment]
Did FOMM work prior to you bringing MO into the mix? I know basically zero about how MO works, aside from the description given on the Nexus download page...what I'm wondering about is whether FOMM is somehow fooled by MO's virtual data (and I did see that MO is supposed to work w/FOMM but it wouldn't be the first time I've seen tool-caused fatal conflicts).

**Comment by GrantSP** [comment]
Years ago I used the original FOMM but I haven't used your fork before.
As to MO, let me add some info for you.
MO makes absolutely no changes to either the game Data folder folder or any registry settings.
It functions by creating a virtual file system into which it loads the mods used by either the game of the tools that act on those mods.
As mentioned above, when I execute FOMM from outside MO it is essentially as though MO doesn't even exist on my machine. There is no code or files indicating any connection with either FOMM or the game(s) that FOMM works on that MO uses.

**Comment by EvilOssie** [comment]
I was just now editing my post to say basically the same thing...that each should not be aware of the other at all.

Dunno what to say, tbh...maybe the un/re-install of FOMM, in the hope that it jars something loose, but that's admittedly about 1/2 step up from "...have you rebooted?"

Can you try this...uninstall MO, then do a fresh install of FOMM and see what happens? I may be totally off-base in thinking that the two of them are somehow together in causing the problem, but I"m really not sure what else to suggest right now.

And a FWIW - you mentioned "...your (my) fork..." of FOMM up there; I had/have no part in the actual building of FOMM; I'm here 'cause I've used most versions of FOMM and/or OBMM and have picked up a few things along the way that has helped others in the past. I make no claim to being The Authority on it, tho.

**Comment by GrantSP** [comment]
Fixed it!
It appears to be a file/folder write permission error. At least that is what I can put it down to.

The fact that the error was being generated upon the 'Update required' dialog I posted about earlier, made me think that something wasn't being set in the program when FOMM tried to make changes to that location.
Completely uninstalled FOMM and purged any reference from my disk or the registry to anything even remotely related to it.
That included any 'Install Info' or 'mods' folders that were generated and all FOMM registry entries.

Since I was getting errors with Fallout 3 I decided to try and install it and work with it first. All looked good until after selecting the locations for those folders. This time I was allowed, and I thought all was good, but after doing the same for FNV, I again had to recheck the "which game" selector to FO3 and bingo! the error again.

So retry number 2, complete uninstall again and this time I decided to move the 'Install Info' & 'mods' folders to completely different locations.
Previously both those locations were sub-folders to my games:
_**C:\Games\Fallouts\**_ & _**C:\Program Files (x86)\Steam\SteamApps\common\Fallout New Vegas\**_

Now I placed those folders as sub-folders under the install directory of FOMM like this:
_**C:\Games\Utils\FOMM\FalloutNV\mods**_
_**C:\Games\Utils\FOMM\FalloutNV\Install Info**_

and 
_**C:\Games\Utils\FOMM\Fallout3\Install Info**_
_**C:\Games\Utils\FOMM\Fallout3\mods**_

Success!
I don't know why that makes a difference, no folders on my system are under UAC and at any rate I have full administrator rights. Even the *user.config* is in a non-system folder so I have not the foggiest what is happening.
But there you have it. When FOMM tries to install its folders under my Fallout3 game folder, it bugs out whereas they are fine under the FalloutNV folder. If anything I would've thought the opposite since Fallout3 is away from the _**Program Files**_ folder which is usually a problem.

**Comment by niveuseverto** [comment]
Will fix this behavior (or at least FOMM will display more meaningful messages) ASAP
