### ISSUE TITLE
Crash When Selecting "Settings"

### ISSUE THREAD

**Issue by kbarsotti** [foesmm/fomm#29]
When I open FOMM and click the "Settings" button, the application crashes.  The following exception data was written into crashdump.txt:

Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by niveuseverto** [comment]
Try new version, this issue is fixed in latest release.

**Comment by kbarsotti** [comment]
The latest release that I am seeing is v0.14.11.12 - the version on which I am experiencing the issue.  Is there a newer release located elsewhere?

**Comment by LeftyMouse** [comment]
Also seeing this in 0.14.11.12 when I click on "Settings".

Monday, April 13, 2015 - 5:20:34
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ikenjake** [comment]
I too am getting this error

Monday, April 20, 2015 - 7:56:35 AM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ikenjake** [comment]
I reinstalled fallout NV and now I get this error:



See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
fomm
    Assembly Version: 0.14.11.12
    Win32 Version: 0.14.11.12
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/fomm.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34239 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
SevenZipSharp
    Assembly Version: 0.64.3890.29348
    Win32 Version: 0.64.3890.29348
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/SevenZipSharp.DLL
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34243 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
fomm.Transactions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/fomm.Transactions.DLL
----------------------------------------
ChinhDo.Transactions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/ChinhDo.Transactions.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.34230 built by: FX452RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
GeMod.Interface
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/GeMod.Interface.DLL
----------------------------------------
dotnetscript0
    Assembly Version: 0.0.0.0
    Win32 Version: 0.14.11.12
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/fomm.exe
----------------------------------------
fomm.Scripting
    Assembly Version: 0.14.11.12
    Win32 Version: 0.14.11.12
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/fomm.Scripting.DLL
----------------------------------------
dotnetscript1
    Assembly Version: 0.0.0.0
    Win32 Version: 0.14.11.12
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/fomm.exe
----------------------------------------
dotnetscript2
    Assembly Version: 0.0.0.0
    Win32 Version: 0.14.11.12
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/fomm.exe
----------------------------------------
dotnetscript3
    Assembly Version: 0.0.0.0
    Win32 Version: 0.14.11.12
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/fomm.exe
----------------------------------------
dotnetscript4
    Assembly Version: 0.0.0.0
    Win32 Version: 0.14.11.12
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/fomm.exe
----------------------------------------
dotnetscript5
    Assembly Version: 0.0.0.0
    Win32 Version: 0.14.11.12
    CodeBase: file:///C:/Program%20Files%20(x86)/FOMM/fomm.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by prd1** [comment]
Same issue, same output:

Saturday, June 6, 2015 - 5:09:11 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by FireCulex** [comment]
Wednesday, June 24, 2015 - 11:51:53 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.IntPtr.ToInt32()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

waiting patiently for a fix 4 months later.

**Comment by L0FKA** [comment]
Look for last commit, that what they mean,it's novv a v0.14.11.13 btvv they  could use appveyor build server to get nightly builds(artifacts) for you :)

**Comment by UniversityOfPi** [comment]
Not having a clear/easy way of getting 0.14.11.13, even over a year later, doesn't help.

`Saturday, August 6, 2016 - 22:22:10 
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

Tried to compile and that didn't work because I have VS2015, and the legacy DirectX SDK isn't installed on my system. This is a serious hassle to work around, but I already sunk 50 minutes into this, so I'll keep at it a bit longer and update here if I ever get it to compile. (if I don't, I don't guarantee any updates)

**Comment by RapsStepFather** [comment]
I just installed FOMM 0.14.11.12 for the first time. I'm very new to modding and so far have had no trouble except that when I click on settings for Fallout 3 mods it gives me a StackOverflow error, any help would be greatly appreciated.

August 7, 2016 - 11:24:02 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Combine12** [comment]
Same issue here.

`29 October 2016 - 05:14:09 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`
This doesn't happen with 0.13

**Comment by EpicestGamer** [comment]
Has anyone found a solution? I would REALLY like to change my custom launch command (If there is no solution, can somebody give me instructions to do it manually)

I've tried using -setup, -no-uac-check (because it seems to be something with UAC) I've tried running as admin... using -setup i get a slightly different crash report, but I think it stems from the same bug.

With -setup
```
Sunday, April 30, 2017 - 3:34:50 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.Games.FalloutNewVegas.FalloutNewVegasGameMode.HandleStandaloneArguments(String[] p_strArgs)
   at Fomm.Program.Main(String[] args)

```

Without -setup
```
Sunday, April 30, 2017 - 3:35:44 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by boycad** [comment]
I can't be much help, but I can offer maybe something. I haven't used Fomm since upgrading to Windows 10, but it was sensitive to UAC security and authority settings.  The worst problem I had with it‎ was the relatively well documented conflict it had with NMM. That caused both programs to crash out totally. But NMM has advanced quite some since then. ‎I guess it's nothing to do with that.  I hope you've tried running it *not* elevated, because I think that's how I ran it too. It would be nice to have some basic information about using Fomm with window 10.  It shouldn't be too hard to have it running. If you like, I could fire it up this evening and see what happens. I'd be surprised if it didn't work, but the install is still there. Also, you could try posting on STEP's FNV forums.Otherwise, good luck.                                                                                                                                                                                                    ~bc                                                                                                                                                                                                                From: MikeSent: Sunday, April 30, 2017 2:36 PMTo: foesmm/fommReply To: foesmm/fommCc: SubscribedSubject: Re: [foesmm/fomm] Crash When Selecting "Settings" (#29)Has anyone found a solution? I would REALLY like to change my custom launch command (If there is no solution, can somebody give me instructions to do it manually)
I've tried using -setup, -no-uac-check (because it seems to be something with UAC) I've tried running as admin... using -setup i get a slightly different crash report, but I think it stems from the same bug.
With -setup
Sunday, April 30, 2017 - 3:34:50 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.Games.FalloutNewVegas.FalloutNewVegasGameMode.HandleStandaloneArguments(String[] p_strArgs)
   at Fomm.Program.Main(String[] args)


Without -setup
Sunday, April 30, 2017 - 3:35:44 PM
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/foesmm/fomm","title":"foesmm/fomm","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/foesmm/fomm"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EpicestGamer in #29: Has anyone found a solution? I would REALLY like to change my custom launch command (If there is no solution, can somebody give me instructions to do it manually)\r\n\r\nI've tried using -setup, -no-uac-check (because it seems to be something with UAC) I've tried running as admin... using -setup i get a slightly different crash report, but I think it stems from the same bug.\r\n\r\nWith -setup\r\n```\r\nSunday, April 30, 2017 - 3:34:50 PM\r\nFomm 0.14.11.12\r\nOS version: Microsoft Windows NT 6.2.9200.0\r\n\r\nSystem.OverflowException: Arithmetic operation resulted in an overflow.\r\n   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()\r\n   at Fomm.Util.UacUtil.get_IsElevated()\r\n   at Fomm.SettingsForm.LoadGeneralSettings()\r\n   at Fomm.SettingsForm..ctor()\r\n   at Fomm.Games.FalloutNewVegas.FalloutNewVegasGameMode.HandleStandaloneArguments(String[] p_strArgs)\r\n   at Fomm.Program.Main(String[] args)\r\n\r\n```\r\n\r\nWithout -setup\r\n```\r\nSunday, April 30, 2017 - 3:35:44 PM\r\nFomm 0.14.11.12\r\nOS version: Microsoft Windows NT 6.2.9200.0\r\n\r\nSystem.OverflowException: Arithmetic operation resulted in an overflow.\r\n   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()\r\n   at Fomm.Util.UacUtil.get_IsElevated()\r\n   at Fomm.SettingsForm.LoadGeneralSettings()\r\n   at Fomm.SettingsForm..ctor()\r\n   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)\r\n   at System.Windows.Forms.Control.OnClick(EventArgs e)\r\n   at System.Windows.Forms.Button.OnClick(EventArgs e)\r\n   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)\r\n   at System.Windows.Forms.Control.WmMouseUp(Message\u0026 m, MouseButtons button, Int32 clicks)\r\n   at System.Windows.Forms.Control.WndProc(Message\u0026 m)\r\n   at System.Windows.Forms.ButtonBase.WndProc(Message\u0026 m)\r\n   at System.Windows.Forms.Button.WndProc(Message\u0026 m)\r\n   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)\r\n\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/foesmm/fomm/issues/29#issuecomment-298258846"}}}

**Comment by kbarsotti** [comment]
The latest release of this seems to have resolved the issue!
