### ISSUE TITLE
Settings Tab Causes Crashes

### ISSUE THREAD

**Issue by OpZinE** [foesmm/fomm#61]
Friday, February 10, 2017 - 19:20:54
Fomm 0.14.11.12
OS version: Microsoft Windows NT 6.2.9200.0

System.OverflowException: Arithmetic operation resulted in an overflow.
   at Fomm.Util.UacUtil.get_IsUACOperatingSystem()
   at Fomm.Util.UacUtil.get_IsElevated()
   at Fomm.SettingsForm.LoadGeneralSettings()
   at Fomm.SettingsForm..ctor()
   at Fomm.MainForm.bSettings_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I need some help. Every time I try to open the settings tab, I get this crash dump file. Please help and comment any fixes.

**Comment by vulchor** [comment]
Same problem here, crash dump is exactly identical to yours.

**Comment by niveuseverto** [comment]
Will be upload update in next week or so.
Stay tuned!
